# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Admin Password
description: Test Site
baseurl: ""
url: https://adminpassword.eu

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Domonkos
  description:
    - Working to make a better tomorrow for all mankind
    - Th–µ shadows are fading
    - This cake is a lie
  cv: assets/cv.pdf
  address:
    - Black Mesa
    - Department Algebra Analytics
    - 123 Main St, Anytown, USA
  contact:
    office: Foobar Hall 1.23
    phone: +1 234 567 890
    email: username@domain.com
  demo: https://adminpassword.eu
  source: https://adminpassword.eu
  profiles:
    facebook: https://www.facebook.com
    twitter: https://twitter.com
    instagram: https://www.instagram.com
    linkedin: https://www.linkedin.com
    stackoverflow: https://stackoverflow.com
    github: https://github.com

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
